#include <hidef.h>      /* common defines and macros */
#include "derivative.h"      /* derivative-specific definitions */

#define onda PTM_PTM1
#define delta_mezzi 2 //faccio tutto il calcolo delta=T_voluta/T_clk
#define equal TFLG1_C3F //sarebbe il flag di comparazione del canale 3
#define soglia TC3 //la comparazione è fatta sul canale 3
void main(void) {

  
  
  /* put your own code here */
  CPMUPROT=0x00; // disabilito la protezione del registro di configurazione
  CPMUOSC=0x00; //scelgo l'internal oscillatore mettendo a 0 l'msb,se lo metto a uno scelgo l'oscillatore esterno
  CPMUCLKS=0x80; //seleziono il PLL come sorgente di clock
  DDRM=0x02;
  //when the bit LOCK in CPMUFLG is ‘1’ the clock signal generated by the PLL is stable and can be used.
  //f_pll=12.5 MHZ , con SYNDIV=25 POSTDIV=3
  
  
	EnableInterrupts;

  
  onda=1;
  CPMUPOSTDIV_POSTDIV=1;  //setto postdiv=1
  
  while (!CPMUFLG_LOCK); //finchè non diventa stabile il segnale di clock
  
  TSCR1=0x90; // Abilitiamo il tcnt (TEN) e il tffca (fast flag clear abilitato)
  TSCR2=0x04; // settiamo il PR=4
  TIOS=0x08; //attivo IOS3 per abilitare l'output compare 3
  
  soglia=TCNT+delta_mezzi;
  
  while (1) 
  {
    if(equal) 
     {
      
       onda^=1;
       soglia=TCNT+delta_mezzi;
     }
  
  
    _FEED_COP(); /* feeds the dog */
  } /* loop forever */
  /* please make sure that you never leave main */
}
